CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_document_information (
    id SERIAL UNIQUE,
    celex_id VARCHAR (20) NOT NULL,
	celex_url VARCHAR (100) NOT NULL,
	original_text JSONB,
	annotated_text JSONB,
    PRIMARY KEY (celex_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_definition_term (
	term_id SERIAL NOT NULL,
	doc_id INT REFERENCES lexdrafter_energy_document_information(id),
	term TEXT NOT NULL,
	sentences JSONB,
	PRIMARY KEY (term_id, doc_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_term_explanation (
    id SERIAL NOT NULL,
    term_id INT,
    doc_id INT,
    explanation TEXT,
    definition_type VARCHAR(20) NOT NULL DEFAULT 'static',
	reference_list JSONB,
    PRIMARY KEY (term_id, doc_id),
    FOREIGN KEY (term_id, doc_id) REFERENCES lexdrafter_energy_definition_term(term_id, doc_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_term_relations (
	id SERIAL,
	doc_id INT,
	term_id1 INT,
	term TEXT NOT NULL,
	relationship_id INT REFERENCES lexdrafter_relationship (id),
	PRIMARY KEY (id),
	FOREIGN KEY (doc_id, term_id1) REFERENCES lexdrafter_energy_definition_term(doc_id, term_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_relationship (
	id SMALLINT GENERATED BY DEFAULT AS IDENTITY (CYCLE),
	description VARCHAR NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_progress_table (
	celex_id VARCHAR (20) NOT NULL,
	status TEXT NOT NULL,
    PRIMARY KEY (celex_id)
);

--- Query to find out how many documents has definition article
SELECT DISTINCT(celex_id)
FROM lexdrafter_energy_articles
WHERE article_title LIKE '%Definition%'
   OR article_title LIKE '%Definitions%';
   
--- Query to find out the distribution of definitions present in different documents
SELECT d.celex_id, t.doc_id, COUNT(t.term_id) AS term_count
FROM lexdrafter_energy_definition_term as t
JOIN lexdrafter_energy_document_information as d
ON t.doc_id = d.id
GROUP BY d.celex_id, t.doc_id
ORDER BY term_count ASC;

--- Query to find out one Celex document not considered to extract the definitions
--- 32013R0617 due to high complexity in definitions present
SELECT DISTINCT(a.celex_id)
FROM lexdrafter_energy_articles a
WHERE (a.article_title LIKE '%Definition%' OR a.article_title LIKE '%Definitions%')
  AND NOT EXISTS (
    SELECT 1
    FROM lexdrafter_energy_document_information b
    WHERE a.celex_id = b.celex_id
  );


--- Analysis of extracted Definitions:
SELECT DISTINCT(term_id) FROM lexdrafter_energy_definition_term --- term present
SELECT * FROM lexdrafter_energy_document_information -- document information
SELECT * FROM lexdrafter_energy_term_explanation -- definition

--- Query to find the legal terms that are having single or multiple occurrence in definition fragment
SELECT
  COUNT(CASE WHEN doc_count = 1 THEN 1 END) AS single_occurrence_terms,
  COUNT(CASE WHEN doc_count > 1 THEN 1 END) AS multiple_occurrence_terms
FROM (
  SELECT
    term_id,
    COUNT(doc_id) AS doc_count
  FROM lexdrafter_energy_term_explanation
  GROUP BY term_id
) AS subquery;

--- Query to find out terms that are not properly extracted there no fragments are present
SELECT DISTINCT(t1.term_id)
FROM lexdrafter_energy_definition_term t1
LEFT JOIN lexdrafter_energy_term_explanation t2 ON t1.term_id = t2.term_id
WHERE t2.term_id IS NULL;

--- Analysis of Definition fragments
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%as defined in%' --106 fragments
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%referred to in%' --8 fragments
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%provided for in%' --3 fragments
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%the meaning of%' --1 fragment
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%laid down in%' --3 fragments
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%according to the definition in%' -- 0 fragment
SELECT * FROM lexdrafter_energy_term_explanation WHERE explanation LIKE '%as stipulated in%' -- 0 fragment

--- Substitute of "as defined in" tried
SELECT *
FROM lexdrafter_energy_term_explanation
WHERE explanation LIKE '%according to the definition in%'
   OR explanation LIKE '%as stipulated in%'
   OR explanation LIKE '%per the definition in%'
   OR explanation LIKE '%in accordance with the description in%'
   OR explanation LIKE '%as described in%'
   OR explanation LIKE '%following the definition in%'
   OR explanation LIKE '%in line with the definition in%'
   OR explanation LIKE '%based on the definition in%'
   OR explanation LIKE '%referencing the definition in%'
   OR explanation LIKE '%as outlined in%';

-- -- Create a new table for split
-- CREATE TABLE lexdrafter_energy_document_split (
--     celex_id VARCHAR(255),
--     split VARCHAR(255)
-- );

-- -- Create a CTE with the row numbers
-- WITH cte AS (
--     SELECT
--         celex_id,
--         ROW_NUMBER() OVER (ORDER BY celex_id) AS row_num
--     FROM lexdrafter_energy_document_information
-- )
-- INSERT INTO lexdrafter_energy_document_split (celex_id, split)
-- SELECT
--     cte.celex_id,
--     CASE
--         WHEN cte.row_num <= 65 THEN 'train'
--         WHEN cte.row_num <= 82 THEN 'validate'
--         ELSE 'test'
--     END AS split
-- FROM cte;

-- SELECT * FROM lexdrafter_energy_document_split

-- -- Dataset Creation
-- CREATE TABLE lexdrafter_energy_document_split (
--     celex_id VARCHAR(20),
--     split VARCHAR(20)
-- );


-- WITH cte AS (
--     SELECT
--         celex_id,
--         SUBSTRING(celex_id, 2, 4) AS celex_year,
--         ROW_NUMBER() OVER (ORDER BY celex_id) AS row_num
--     FROM lexdrafter_energy_document_information
-- )
-- INSERT INTO lexdrafter_energy_document_split (celex_id, split)
-- SELECT
--     cte.celex_id,
--     CASE
--         WHEN cte.celex_year BETWEEN '2005' AND '2018' THEN 'train'
--         WHEN cte.celex_year BETWEEN '2019' AND '2020' THEN 'validate'
--         WHEN cte.celex_year BETWEEN '2021' AND '2023' THEN 'test'
--         ELSE 'unknown'
--     END AS split
-- FROM cte;

-- SELECT * FROM lexdrafter_energy_term_explanation

-- CREATE TABLE lexdrafter_energy_data_split AS
-- SELECT
--     ds.celex_id,
--     ds.split,
--     te.term_id,
--     te.doc_id,
--     te.explanation
-- FROM lexdrafter_energy_document_split ds
-- JOIN lexdrafter_energy_document_information di ON ds.celex_id = di.celex_id
-- JOIN lexdrafter_energy_term_explanation te ON di.id = te.doc_id;
