from .section_extraction import title_extraction, document_information
from .database.database_insert import insert_postgres, star_schema_postgres, insert_article_aux
from .database.database_connection import postgres_connection, opensearch_connection
from .database.database_read import process_records_in_batches as process_records_in_batches, opensearch_valid_record_query as opensearch_valid_record_query
from .database.database_utils import check_for_existing_records, check_for_valid_documents_to_consider as check_for_valid_documents_to_consider
from .database.database_update import update_postgres, update_processed_articles_records, update_opensearch_batch as update_opensearch_batch
from .schema_creation import split_fragment, document_fragment
from .helper_script import article_text_completion