CREATE TABLE lexdrafter_energy_titles (
	celex_id VARCHAR (20) PRIMARY KEY,
	title_text VARCHAR (65535) NOT NULL
);

CREATE TABLE lexdrafter_energy_recitals(
	celex_id VARCHAR (20) NOT NULL,
	recital_fragment_number INT NOT NULL,
	recital_fragment_original_value INT NOT NULL,
	recital_subfragment_number INT NOT NULL,
	recital_text VARCHAR (65535),
	PRIMARY KEY (celex_id, recital_fragment_number, recital_subfragment_number),
	FOREIGN KEY (celex_id)
      REFERENCES lexdrafter_energy_titles (celex_id)
);

CREATE TABLE lexdrafter_energy_chapters (
	celex_id VARCHAR (20) NOT NULL,
	chapter_number INT NOT NULL,
	chapter_title VARCHAR (65535),
	PRIMARY KEY (celex_id, chapter_number),
	FOREIGN KEY (celex_id)
      REFERENCES lexdrafter_energy_titles (celex_id)
);


CREATE TABLE lexdrafter_energy_sections (
	celex_id VARCHAR (20) NOT NULL,
	chapter_number INT NOT NULL,
	section_number INT NOT NULL,
	section_title VARCHAR (65535),
	PRIMARY KEY (celex_id, chapter_number, section_number),
	FOREIGN KEY (celex_id)
      REFERENCES lexdrafter_energy_titles (celex_id)
);


CREATE TABLE lexdrafter_energy_articles (
	celex_id VARCHAR (20) NOT NULL,
	chapter_number INT NOT NULL,
	section_number INT NOT NULL,
	article_number INT NOT NULL,
	article_title VARCHAR (65535),
	article_fragment_number INT NOT NULL,
	article_fragment_original_value INT NOT NULL,
	article_subfragment_number INT NOT NULL,
    article_text VARCHAR (65535),
	processed_flag CHAR (1),
	PRIMARY KEY (celex_id, chapter_number, section_number, article_number, article_fragment_number, article_subfragment_number),
	FOREIGN KEY (celex_id)
      REFERENCES lexdrafter_energy_titles (celex_id)
);


CREATE TABLE lexdrafter_energy_annexs (
	celex_id VARCHAR (20) NOT NULL,
	annex_number VARCHAR (10) NOT NULL,
	annex_fragment_number INT NOT NULL,
	annex_subfragment_number INT NOT NULL,
	annex_title VARCHAR (65535),
	annex_text VARCHAR (65535),
	PRIMARY KEY (celex_id, annex_number, annex_fragment_number, annex_subfragment_number),
	FOREIGN KEY (celex_id)
      REFERENCES lexdrafter_energy_titles (celex_id)
);


CREATE TABLE IF NOT EXISTS lexdrafter_energy_article_aux
(
    article_info text,
    flag text,
	PRIMARY KEY (article_info)
);

------

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_document_information (
    id SERIAL UNIQUE,
    celex_id VARCHAR (20) NOT NULL,
	celex_url VARCHAR (100) NOT NULL,
	original_text JSONB,
	annotated_text JSONB,
    PRIMARY KEY (celex_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_definition_term (
	term_id SERIAL NOT NULL,
	doc_id INT REFERENCES lexdrafter_energy_document_information(id),
	term TEXT NOT NULL,
	sentences JSONB,
	PRIMARY KEY (term_id, doc_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_term_explanation (
	id SERIAL NOT NULL,
	term_id INT,
	doc_id INT,
	explanation TEXT,
	PRIMARY KEY (term_id, doc_id),
	FOREIGN KEY (term_id, doc_id) REFERENCES lexdrafter_energy_definition_term(term_id, doc_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_term_relations (
	id SERIAL,
	doc_id INT,
	term_id1 INT,
	term TEXT NOT NULL,
	relationship_id INT REFERENCES lexdrafter_relationship (id),
	PRIMARY KEY (id),
	FOREIGN KEY (doc_id, term_id1) REFERENCES lexdrafter_energy_definition_term(doc_id, term_id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_relationship (
	id SMALLINT GENERATED BY DEFAULT AS IDENTITY (CYCLE),
	description VARCHAR NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lexdrafter_energy_progress_table (
	celex_id VARCHAR (20) NOT NULL,
	status TEXT NOT NULL,
    PRIMARY KEY (celex_id)
);

SELECt * FROM lexdrafter_energy_progress_table
SELECT * FROM lexdrafter_energy_document_information

SELECT d.celex_id, t.doc_id, COUNT(t.term_id) AS term_count
FROM lexdrafter_energy_definition_term as t
JOIN lexdrafter_energy_document_information as d
ON t.doc_id = d.id
GROUP BY d.celex_id, t.doc_id
ORDER BY term_count ASC;

SELECT * FROM lexdrafter_energy_definition_term WHERE doc_id = 41
SELECT * FROM lexdrafter_energy_term_explanation WHERE term_id = 493 and doc_id = 41

SELECT * FROM lexdrafter_energy_term_explanation

SELECT * FROM lexdrafter_energy_document_information where id = 46
SELECT * FROM lexdrafter_energy_definition_term where doc_id = 46


SELECT * FROM lexdrafter_energy_document_information


SELECT *
FROM lexdrafter_energy_document_information
ORDER BY celex_id ASC;

-- Create a new table for split
CREATE TABLE lexdrafter_energy_document_split (
    celex_id VARCHAR(255),
    split VARCHAR(255)
);

-- Create a CTE with the row numbers
WITH cte AS (
    SELECT
        celex_id,
        ROW_NUMBER() OVER (ORDER BY celex_id) AS row_num
    FROM lexdrafter_energy_document_information
)
INSERT INTO lexdrafter_energy_document_split (celex_id, split)
SELECT
    cte.celex_id,
    CASE
        WHEN cte.row_num <= 65 THEN 'train'
        WHEN cte.row_num <= 82 THEN 'validate'
        ELSE 'test'
    END AS split
FROM cte;

SELECT * FROM lexdrafter_energy_document_split

-- Dataset Creation
CREATE TABLE lexdrafter_energy_document_split (
    celex_id VARCHAR(20),
    split VARCHAR(20)
);


WITH cte AS (
    SELECT
        celex_id,
        SUBSTRING(celex_id, 2, 4) AS celex_year,
        ROW_NUMBER() OVER (ORDER BY celex_id) AS row_num
    FROM lexdrafter_energy_document_information
)
INSERT INTO lexdrafter_energy_document_split (celex_id, split)
SELECT
    cte.celex_id,
    CASE
        WHEN cte.celex_year BETWEEN '2005' AND '2018' THEN 'train'
        WHEN cte.celex_year BETWEEN '2019' AND '2020' THEN 'validate'
        WHEN cte.celex_year BETWEEN '2021' AND '2023' THEN 'test'
        ELSE 'unknown'
    END AS split
FROM cte;

SELECT * FROM lexdrafter_energy_term_explanation

CREATE TABLE lexdrafter_energy_data_split AS
SELECT
    ds.celex_id,
    ds.split,
    te.term_id,
    te.doc_id,
    te.explanation
FROM lexdrafter_energy_document_split ds
JOIN lexdrafter_energy_document_information di ON ds.celex_id = di.celex_id
JOIN lexdrafter_energy_term_explanation te ON di.id = te.doc_id;
